language: node_js
node_js: node
branches:
  only:
    - main
cache:
  directories:
    - node_modules
env:
  - CI = false
before_deploy:
  - npm i
  - npm install netlify-cli -g
  - npm run build
deploy:
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p --dir ./build
