language: node_js
node_js: node
branches:
  only:
    - main
cache:
  directories:
    - node_modules
script:
  - node -v
before_deploy:
  - npm i
  - npm run build
deploy:
  provider: script
  script: node -v
  skip_cleanup: true
  on:
    branch: main
