language: node_js
node_js: node
cache:
  directories:
    - node_modules
script: 'true'
before_deploy:
  - npm install netlify-cli -g
  - CI=false npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: netlify deploy -s $NET_SITE_ID -a $NETLIFY_AUTH_TOKEN -p --dir ./build
  on:
    all_branches: true
