language: node_js
node_js: node
cache:
  directories:
    - node_modules
env:
  - CI = false
script: 'true'
before_deploy:
  - npm install netlify-cli -g
  - npm run build
deploy:
  provider: script
  script: netlify deploy -s $NET_SITE_ID -a $NETLIFY_ACCESS_TOKEN -p --dir ./build
  on:
    all_branches: true
